#!/bin/bash

# Inspired from https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes-for-v3.x

set -e -o pipefail
set -x

basedir="$( cd -P "$( dirname "$0" )" && pwd )"
source "$basedir/../bin/common.sh"
source "$basedir/../config/versions.sh"
source "$basedir/lib/utils"
source "$basedir/lib/s3.lib.sh"
source "$basedir/lib/deb.lib.sh"

pkgs_url="https://mirrors.edge.kernel.org/ubuntu/pool"

# Tool required to upload nginx build artifacts
which aws >/dev/null || apt-get install awscli
# Tool required to unarchived .deb data.tar.zst archives (started with ubuntu 22.04)
which zstd >/dev/null || apt-get install zstd
# Tool required for building modsecurity
which aclocal >/dev/null || apt-get install automake libssl-dev libpcre3-dev libxml2-dev libcurl4-openssl-dev

validate_env

MODSECURITY_VERSION=${1:-$default_modsecurity_version}
MODSECURITY_DIR="modsecurity-v${MODSECURITY_VERSION}"
MODSECURITY_TARBALL="${MODSECURITY_DIR}.tar.gz"
MODSECURITY_URL="https://github.com/SpiderLabs/ModSecurity/releases/download/v${MODSECURITY_VERSION}/${MODSECURITY_TARBALL}"

# Setup constants for Ubuntu packages version according to the used stack
# We declare associative array (a hash), syntax is
# declare -A var_name=(["key1"]="val1" ["key2"]="val2" ...)
# echo ${var_name[key1]} # display: "val1"
declare -A geoip_version=(["scalingo-22"]="1.6.12-6build1")
declare -A yajl_version=(["scalingo-22"]="2.1.0-3build2")
declare -A lmdb_version=(["scalingo-22"]="0.9.24-1build2")
declare -A libfuzzy_version=(["scalingo-22"]="2.14.1+git20180629.57fcfff-2")
declare -A lua_version=(["scalingo-22"]="5.4.7-1")

tempdir=$(mktmpdir modsecurity)
cd $tempdir

install_dir="/app/vendor/modsecurity"
mkdir -p "${install_dir}"

# Handle minimal stacks
deps_stack=$STACK
if [[ "$STACK" =~ .*minimal$ ]] ; then
  deps_stack=$(echo $STACK | sed -e 's/-minimal//')
fi

status "Packaging libgeoip ${geoip_version[$deps_stack]}"

curl --remote-name --location "${pkgs_url}/main/g/geoip/libgeoip-dev_${geoip_version[$deps_stack]}_amd64.deb"
curl --remote-name --location "${pkgs_url}/main/g/geoip/libgeoip1_${geoip_version[$deps_stack]}_amd64.deb"
extract_deb "libgeoip-dev_${geoip_version[$deps_stack]}_amd64.deb" "${install_dir}"
extract_deb "libgeoip1_${geoip_version[$deps_stack]}_amd64.deb" "${install_dir}"

status "Packaging libyajl ${yajl_version[$deps_stack]}"
curl --remote-name --location --silent "${pkgs_url}/main/y/yajl/libyajl-dev_${yajl_version[$deps_stack]}_amd64.deb"
curl --remote-name --location --silent "${pkgs_url}/main/y/yajl/libyajl2_${yajl_version[$deps_stack]}_amd64.deb"
extract_deb "libyajl-dev_${yajl_version[$deps_stack]}_amd64.deb" "${install_dir}"
extract_deb "libyajl2_${yajl_version[$deps_stack]}_amd64.deb" "${install_dir}"

status "Packaging liblmdb ${lmdb_version[$deps_stack]}"
curl --remote-name --location --silent "${pkgs_url}/main/l/lmdb/liblmdb-dev_${lmdb_version[$deps_stack]}_amd64.deb"
curl --remote-name --location --silent "${pkgs_url}/main/l/lmdb/liblmdb0_${lmdb_version[$deps_stack]}_amd64.deb"
extract_deb "liblmdb-dev_${lmdb_version[$deps_stack]}_amd64.deb" "${install_dir}"
extract_deb "liblmdb0_${lmdb_version[$deps_stack]}_amd64.deb" "${install_dir}"

status "Packaging ssdeep (libfuzzy) ${libfuzzy_version[$deps_stack]}"
curl --remote-name --location --silent "${pkgs_url}/universe/s/ssdeep/libfuzzy2_${libfuzzy_version[$deps_stack]}_amd64.deb"
curl --remote-name --location --silent "${pkgs_url}/universe/s/ssdeep/libfuzzy-dev_${libfuzzy_version[$deps_stack]}_amd64.deb"
extract_deb "libfuzzy2_${libfuzzy_version[$deps_stack]}_amd64.deb" "${install_dir}"
extract_deb "libfuzzy-dev_${libfuzzy_version[$deps_stack]}_amd64.deb" "${install_dir}"

status "Packaging Lua (liblua5.4) ${lua_version[$deps_stack]}"
curl --remote-name --location --silent "${pkgs_url}/main/l/lua5.4/liblua5.4-0_${lua_version[$deps_stack]}_amd64.deb"
curl --remote-name --location --silent "${pkgs_url}/main/l/lua5.4/liblua5.4-dev_${lua_version[$deps_stack]}_amd64.deb"
extract_deb "liblua5.4-0_${lua_version[$deps_stack]}_amd64.deb" "${install_dir}"
extract_deb "liblua5.4-dev_${lua_version[$deps_stack]}_amd64.deb" "${install_dir}"

status "Downloading ModSecurity $MODSECURITY_VERSION"
curl --remote-name --location --silent "$MODSECURITY_URL"
tar --extract --ungzip --file "$MODSECURITY_TARBALL"
pushd "$MODSECURITY_DIR" >/dev/null
  ./build.sh && \
  # SSDEEP is not handled like others, it's not possible to easily tweak the path, doing it manually
  sed -i "s+^SSDEEP_POSSIBLE_PATHS=.*+SSDEEP_POSSIBLE_PATHS=${install_dir}/usr+" "./configure" && \
  sed -i "s+^LUA_POSSIBLE_PATHS=.*+LUA_POSSIBLE_PATHS=${install_dir}/usr+" "./configure" && \
  sed -i "s+LUA_CFLAGS=\"-I\${lua_inc_path}\"+LUA_CFLAGS=\"-I\${lua_inc_path} -I\${lua_inc_path}/../x86_64-linux-gnu\"+" "./configure" && \
  ./configure \
     "--prefix=${install_dir}" \
     "--with-geoip=${install_dir}/usr" \
     "--with-yajl=${install_dir}/usr" \
     "--with-lmdb=${install_dir}/usr" \
     "--with-ssdeep=yes" \
     "--with-lua=${install_dir}/usr" \
     --disable-examples && \
  make -j 4 && \
  make install
popd >/dev/null

status "Uploading package to S3 ${S3_URL}/package/modsecurity-${MODSECURITY_VERSION}.tgz"
package_filepath="package/modsecurity-${MODSECURITY_VERSION}.tgz"
mkdir package
pushd /app/vendor/modsecurity >/dev/null
  tar zcf "${tempdir}/${package_filepath}" .
popd >/dev/null

s3_upload "$S3_BUCKET" "${package_filepath}" "${STACK}/${package_filepath}" > /dev/null
"$basedir/manifest" modsecurity
"$basedir/package-checksum" "modsecurity-${MODSECURITY_VERSION}"

status "Done building ModSecurity $MODSECURITY_VERSION package!"
