#!/usr/bin/env bash

set -e

basedir="$( cd -P "$( dirname "$0" )" && pwd )"
source "$basedir/lib/utils"
source "$basedir/lib/s3"

validate_env

package="$1"

cd $(mktmpdir swift)

echo "-----> Creating checksum for ${package}"

s3_download "package/${package}.tgz"

mkdir -p ./package
md5 "${package}.tgz" > "package/${package}.md5"
s3_upload "package/${package}.md5"
