#!/usr/bin/env bash

function validate_env() {
	if [ -z "$S3_BUCKET" ]; then
		echo "Must set S3_BUCKET environment variable" >&2
		exit 1
	fi

	if [[ -z "$AWS_ACCESS_KEY_ID" \
			|| -z "${AWS_SECRET_ACCESS_KEY}" \
			|| -z "${AWS_SESSION_TOKEN}" ]]
	then
		echo "Please export AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY and AWS_SESSION_TOKEN from AWS console." >&2
		exit 1
	fi
}

function mktmpdir() {
	tempdir="$( mktemp -t $1_XXXX )"
	rm -rf "${tempdir}"
	mkdir -p "${tempdir}"
	echo "${tempdir}"
}

function md5() {
	md5sum $1 | awk '{print $1}'
}
